export const DEFAULT_FAQS = [
    {
        question: "آیا نسخه رایگان محدودیت دارد؟",
        answer:
            "پلن پایه برای شروع رایگان است و امکان ثبت فروش، فاکتور و انبارداری ساده را فراهم می‌کند. برای کاربران بیشتر، گزارش‌های پیشرفته و حسابداری کامل می‌توانید به پلن حرفه‌ای ارتقا دهید.",
        order: 1,
        isActive: true,
    },
    {
        question: "راه‌اندازی سیستم چقدر زمان می‌برد؟",
        answer:
            "معمولاً در کمتر از یک روز می‌توانید حساب بسازید، محصولات و انبار را تعریف کنید و اولین فاکتور را ثبت کنید. برای مجموعه‌های بزرگ‌تر، تیم پشتیبانی در پیکربندی اولیه همراه شماست.",
        order: 2,
        isActive: true,
    },
    {
        question: "داده‌های قبلی فروشگاه یا حسابداری را می‌توان منتقل کرد؟",
        answer:
            "بله. امکان وارد کردن اطلاعات محصولات، موجودی و مشتریان از طریق فایل اکسل وجود دارد. در پلن‌های سازمانی، انتقال داده‌های پیچیده‌تر با کمک تیم استقرار انجام می‌شود.",
        order: 3,
        isActive: true,
    },
    {
        question: "آیا روی موبایل و چند دستگاه قابل استفاده است؟",
        answer:
            "بله. فلش مبتنی بر وب است و از طریق مرورگر روی کامپیوتر، تبلت و موبایل در دسترس است. با یک حساب می‌توانید همزمان از چند دستگاه استفاده کنید.",
        order: 4,
        isActive: true,
    },
    {
        question: "پشتیبانی چگونه انجام می‌شود؟",
        answer:
            "پشتیبانی از طریق چت، تیکت و تماس در دسترس است. در پلن حرفه‌ای پاسخ‌گویی اولویت‌دار و در پلن سازمانی پشتیبانی ۲۴/۷ ارائه می‌شود.",
        order: 5,
        isActive: true,
    },
    {
        question: "امنیت اطلاعات چگونه تضمین می‌شود؟",
        answer:
            "داده‌ها با رمزنگاری منتقل و ذخیره می‌شوند، دسترسی کاربران قابل سطح‌بندی است و پشتیبان‌گیری منظم از اطلاعات انجام می‌گیرد تا در صورت بروز مشکل، بازیابی سریع ممکن باشد.",
        order: 6,
        isActive: true,
    },
]

const BASE_FEATURES = {
    basic: ["۱ کاربر", "ثبت فروش و فاکتور", "انبارداری ساده", "گزارش‌های پایه"],
    pro: [
        "تا ۱۰ کاربر",
        "حسابداری کامل",
        "انبارداری پیشرفته",
        "گزارش‌های تحلیلی",
        "پشتیبانی اولویت‌دار",
    ],
    enterprise: [
        "کاربران نامحدود",
        "چند شعبه و انبار",
        "API و یکپارچه‌سازی",
        "آموزش و استقرار اختصاصی",
        "پشتیبانی ۲۴/۷",
    ],
}

export const DEFAULT_PRICING_PLANS = [
    {
        name: "پایه",
        price: "رایگان",
        period: "",
        billingType: "monthly",
        description: "برای شروع و کسب‌وکارهای کوچک",
        features: BASE_FEATURES.basic,
        cta: "شروع رایگان",
        highlighted: false,
        order: 1,
        isActive: true,
    },
    {
        name: "حرفه‌ای",
        price: "۴۹۰٬۰۰۰",
        period: "تومان / ماه",
        billingType: "monthly",
        description: "مناسب فروشگاه‌ها و شرکت‌های در حال رشد",
        features: BASE_FEATURES.pro,
        cta: "انتخاب پلن حرفه‌ای",
        highlighted: true,
        order: 2,
        isActive: true,
    },
    {
        name: "سازمانی",
        price: "سفارشی",
        period: "",
        billingType: "monthly",
        description: "برای کارخانه‌ها و مجموعه‌های بزرگ",
        features: BASE_FEATURES.enterprise,
        cta: "تماس با فروش",
        highlighted: false,
        order: 3,
        isActive: true,
    },
    {
        name: "پایه",
        price: "رایگان",
        period: "",
        billingType: "yearly",
        description: "برای شروع و کسب‌وکارهای کوچک",
        features: BASE_FEATURES.basic,
        cta: "شروع رایگان",
        highlighted: false,
        order: 1,
        isActive: true,
    },
    {
        name: "حرفه‌ای",
        price: "۴٬۹۰۰٬۰۰۰",
        period: "تومان / سال",
        billingType: "yearly",
        description: "مناسب فروشگاه‌ها و شرکت‌های در حال رشد",
        features: BASE_FEATURES.pro,
        cta: "انتخاب پلن سالانه",
        highlighted: true,
        order: 2,
        isActive: true,
    },
    {
        name: "سازمانی",
        price: "سفارشی",
        period: "",
        billingType: "yearly",
        description: "برای کارخانه‌ها و مجموعه‌های بزرگ",
        features: BASE_FEATURES.enterprise,
        cta: "تماس با فروش",
        highlighted: false,
        order: 3,
        isActive: true,
    },
    {
        name: "پایه",
        price: "۹٬۹۰۰٬۰۰۰",
        period: "تومان / یک‌بار",
        billingType: "lifetime",
        description: "برای شروع و کسب‌وکارهای کوچک",
        features: BASE_FEATURES.basic,
        cta: "خرید دایمی پایه",
        highlighted: false,
        order: 1,
        isActive: true,
    },
    {
        name: "حرفه‌ای",
        price: "۱۹٬۹۰۰٬۰۰۰",
        period: "تومان / یک‌بار",
        billingType: "lifetime",
        description: "مناسب فروشگاه‌ها و شرکت‌های در حال رشد",
        features: BASE_FEATURES.pro,
        cta: "خرید دایمی حرفه‌ای",
        highlighted: true,
        order: 2,
        isActive: true,
    },
    {
        name: "سازمانی",
        price: "سفارشی",
        period: "",
        billingType: "lifetime",
        description: "برای کارخانه‌ها و مجموعه‌های بزرگ",
        features: BASE_FEATURES.enterprise,
        cta: "تماس با فروش",
        highlighted: false,
        order: 3,
        isActive: true,
    },
]
