import "./globals.css";

import {rubik} from "@/app/fonts";
import ThemeProvider from "@/components/providers/ThemeProvider";
import AntdProvider from "@/components/providers/AntdProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html
            lang="fa"
            dir={"rtl"}
            suppressHydrationWarning
        >
        <body className={`${rubik.className}`}>
        <ThemeProvider>
            <AntdProvider>
                <div className={"min-h-screen bg-background"}>
                    {children}
                </div>
            </AntdProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
